# Generated by Django 6.0.7 on 2026-07-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_scored', models.PositiveIntegerField(default=0)),
                ('balls_faced', models.PositiveIntegerField(default=0)),
                ('wickets_taken', models.PositiveIntegerField(default=0)),
                ('overs_bowled', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('runs_conceded', models.PositiveIntegerField(default=0)),
                ('catches', models.PositiveIntegerField(default=0)),
                ('stumpings', models.PositiveIntegerField(default=0)),
                ('did_bat', models.BooleanField(default=False)),
                ('did_bowl', models.BooleanField(default=False)),
                ('batting_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='players.player')),
            ],
            options={
                'ordering': ['-match__match_date'],
                'indexes': [models.Index(fields=['player', 'match'], name='performance_player__d27121_idx')],
                'unique_together': {('player', 'match')},
            },
        ),
    ]
