# Generated by Django 6.0.7 on 2026-07-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precipitation_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('conditions', models.CharField(blank=True, max_length=100)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_cache', to='venues.venue')),
            ],
            options={
                'ordering': ['-forecast_date'],
                'indexes': [models.Index(fields=['venue', 'forecast_date'], name='weather_wea_venue_i_94625a_idx')],
                'unique_together': {('venue', 'forecast_date')},
            },
        ),
    ]
