# Generated by Django 6.0.7 on 2026-07-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('pitch_type', models.CharField(choices=[('BAT', 'Batting Friendly'), ('BWL', 'Bowling Friendly'), ('BAL', 'Balanced'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city'], name='venues_venu_city_4d7e2f_idx'), models.Index(fields=['country'], name='venues_venu_country_a2c1ef_idx')],
            },
        ),
    ]
