# Generated by Django 6.0.7 on 2026-07-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('TEST', 'Test'), ('ODI', 'ODI'), ('T20I', 'T20 International')], max_length=4)),
                ('opponent', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('status', models.CharField(choices=[('SCH', 'Scheduled'), ('LIV', 'Live'), ('CMP', 'Completed'), ('ABN', 'Abandoned')], default='SCH', max_length=3)),
                ('series_name', models.CharField(blank=True, max_length=200)),
                ('is_home', models.BooleanField(default=True)),
                ('cricsheet_identifier', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='venues.venue')),
            ],
            options={
                'ordering': ['-match_date'],
                'indexes': [models.Index(fields=['format', 'match_date'], name='matches_mat_format_03ac04_idx'), models.Index(fields=['opponent'], name='matches_mat_opponen_1468c0_idx'), models.Index(fields=['status'], name='matches_mat_status_a896a5_idx')],
            },
        ),
    ]
