# Generated by Django 6.0.7 on 2026-07-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=4)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('runs_total', models.PositiveIntegerField(default=0)),
                ('wickets_total', models.PositiveIntegerField(default=0)),
                ('batting_average', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bowling_average', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('strike_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('economy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('highest_score', models.PositiveIntegerField(default=0)),
                ('best_bowling', models.CharField(blank=True, max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format_stats', to='players.player')),
            ],
            options={
                'verbose_name_plural': 'Format stats',
                'ordering': ['-matches_played'],
                'indexes': [models.Index(fields=['player', 'format'], name='analytics_f_player__8d4b44_idx')],
                'unique_together': {('player', 'format')},
            },
        ),
    ]
