# Generated by Django 6.0.7 on 2026-07-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cricsheet_identifier', models.CharField(blank=True, max_length=100, unique=True)),
                ('role', models.CharField(choices=[('BAT', 'Batsman'), ('BWL', 'Bowler'), ('AR', 'All-Rounder'), ('WK', 'Wicket-Keeper')], default='BAT', max_length=3)),
                ('batting_style', models.CharField(choices=[('RH', 'Right-Hand Bat'), ('LH', 'Left-Hand Bat')], default='RH', max_length=2)),
                ('bowling_style', models.CharField(choices=[('RF', 'Right-Arm Fast'), ('RM', 'Right-Arm Medium'), ('RS', 'Right-Arm Spin'), ('LF', 'Left-Arm Fast'), ('LM', 'Left-Arm Medium'), ('LS', 'Left-Arm Spin'), ('NA', 'None')], default='NA', max_length=2)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('debut_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['role'], name='players_pla_role_fe7c3e_idx'), models.Index(fields=['is_active'], name='players_pla_is_acti_90e805_idx')],
            },
        ),
    ]
